// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: common.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorCode int32

const (
	ErrorCode_OK                   ErrorCode = 0
	ErrorCode_NOT_LEADER           ErrorCode = 1
	ErrorCode_NO_LEADER            ErrorCode = 2
	ErrorCode_KEY_NOT_FOUND        ErrorCode = 3
	ErrorCode_TRANSACTION_CONFLICT ErrorCode = 4
	ErrorCode_CLUSTER_NOT_READY    ErrorCode = 5
	ErrorCode_STALE_READ           ErrorCode = 6
	ErrorCode_TIMEOUT              ErrorCode = 7
	ErrorCode_STORAGE_ERROR        ErrorCode = 8
	ErrorCode_INVALID_REQUEST      ErrorCode = 9
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0: "OK",
		1: "NOT_LEADER",
		2: "NO_LEADER",
		3: "KEY_NOT_FOUND",
		4: "TRANSACTION_CONFLICT",
		5: "CLUSTER_NOT_READY",
		6: "STALE_READ",
		7: "TIMEOUT",
		8: "STORAGE_ERROR",
		9: "INVALID_REQUEST",
	}
	ErrorCode_value = map[string]int32{
		"OK":                   0,
		"NOT_LEADER":           1,
		"NO_LEADER":            2,
		"KEY_NOT_FOUND":        3,
		"TRANSACTION_CONFLICT": 4,
		"CLUSTER_NOT_READY":    5,
		"STALE_READ":           6,
		"TIMEOUT":              7,
		"STORAGE_ERROR":        8,
		"INVALID_REQUEST":      9,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[0].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[0]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

type ConsistencyLevel int32

const (
	ConsistencyLevel_EVENTUAL          ConsistencyLevel = 0
	ConsistencyLevel_STRONG            ConsistencyLevel = 1
	ConsistencyLevel_SESSION           ConsistencyLevel = 2
	ConsistencyLevel_BOUNDED_STALENESS ConsistencyLevel = 3
)

// Enum value maps for ConsistencyLevel.
var (
	ConsistencyLevel_name = map[int32]string{
		0: "EVENTUAL",
		1: "STRONG",
		2: "SESSION",
		3: "BOUNDED_STALENESS",
	}
	ConsistencyLevel_value = map[string]int32{
		"EVENTUAL":          0,
		"STRONG":            1,
		"SESSION":           2,
		"BOUNDED_STALENESS": 3,
	}
)

func (x ConsistencyLevel) Enum() *ConsistencyLevel {
	p := new(ConsistencyLevel)
	*p = x
	return p
}

func (x ConsistencyLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConsistencyLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[1].Descriptor()
}

func (ConsistencyLevel) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[1]
}

func (x ConsistencyLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConsistencyLevel.Descriptor instead.
func (ConsistencyLevel) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{1}
}

type NodeInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Region        string                 `protobuf:"bytes,3,opt,name=region,proto3" json:"region,omitempty"`
	Started_At    uint64                 `protobuf:"varint,4,opt,name=started_At,json=startedAt,proto3" json:"started_At,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeInfo) Reset() {
	*x = NodeInfo{}
	mi := &file_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeInfo) ProtoMessage() {}

func (x *NodeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeInfo.ProtoReflect.Descriptor instead.
func (*NodeInfo) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

func (x *NodeInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NodeInfo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *NodeInfo) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *NodeInfo) GetStarted_At() uint64 {
	if x != nil {
		return x.Started_At
	}
	return 0
}

var File_common_proto protoreflect.FileDescriptor

const file_common_proto_rawDesc = "" +
	"\n" +
	"\fcommon.proto\x12\x06hermes\"k\n" +
	"\bNodeInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x16\n" +
	"\x06region\x18\x03 \x01(\tR\x06region\x12\x1d\n" +
	"\n" +
	"started_At\x18\x04 \x01(\x04R\tstartedAt*\xbb\x01\n" +
	"\tErrorCode\x12\x06\n" +
	"\x02OK\x10\x00\x12\x0e\n" +
	"\n" +
	"NOT_LEADER\x10\x01\x12\r\n" +
	"\tNO_LEADER\x10\x02\x12\x11\n" +
	"\rKEY_NOT_FOUND\x10\x03\x12\x18\n" +
	"\x14TRANSACTION_CONFLICT\x10\x04\x12\x15\n" +
	"\x11CLUSTER_NOT_READY\x10\x05\x12\x0e\n" +
	"\n" +
	"STALE_READ\x10\x06\x12\v\n" +
	"\aTIMEOUT\x10\a\x12\x11\n" +
	"\rSTORAGE_ERROR\x10\b\x12\x13\n" +
	"\x0fINVALID_REQUEST\x10\t*P\n" +
	"\x10ConsistencyLevel\x12\f\n" +
	"\bEVENTUAL\x10\x00\x12\n" +
	"\n" +
	"\x06STRONG\x10\x01\x12\v\n" +
	"\aSESSION\x10\x02\x12\x15\n" +
	"\x11BOUNDED_STALENESS\x10\x03B+Z)github.com/aadityabinodyadav/hermes/protob\x06proto3"

var (
	file_common_proto_rawDescOnce sync.Once
	file_common_proto_rawDescData []byte
)

func file_common_proto_rawDescGZIP() []byte {
	file_common_proto_rawDescOnce.Do(func() {
		file_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)))
	})
	return file_common_proto_rawDescData
}

var file_common_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_common_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_common_proto_goTypes = []any{
	(ErrorCode)(0),        // 0: hermes.ErrorCode
	(ConsistencyLevel)(0), // 1: hermes.ConsistencyLevel
	(*NodeInfo)(nil),      // 2: hermes.NodeInfo
}
var file_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_proto_init() }
func file_common_proto_init() {
	if File_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_proto_goTypes,
		DependencyIndexes: file_common_proto_depIdxs,
		EnumInfos:         file_common_proto_enumTypes,
		MessageInfos:      file_common_proto_msgTypes,
	}.Build()
	File_common_proto = out.File
	file_common_proto_goTypes = nil
	file_common_proto_depIdxs = nil
}
