// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: hermes.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BeginTransactionRequest_IsolationLevel int32

const (
	BeginTransactionRequest_SNAPSHOT_ISOLATION BeginTransactionRequest_IsolationLevel = 0
	BeginTransactionRequest_SERIALIZABLE       BeginTransactionRequest_IsolationLevel = 1
	BeginTransactionRequest_READ_COMMITTED     BeginTransactionRequest_IsolationLevel = 2
)

// Enum value maps for BeginTransactionRequest_IsolationLevel.
var (
	BeginTransactionRequest_IsolationLevel_name = map[int32]string{
		0: "SNAPSHOT_ISOLATION",
		1: "SERIALIZABLE",
		2: "READ_COMMITTED",
	}
	BeginTransactionRequest_IsolationLevel_value = map[string]int32{
		"SNAPSHOT_ISOLATION": 0,
		"SERIALIZABLE":       1,
		"READ_COMMITTED":     2,
	}
)

func (x BeginTransactionRequest_IsolationLevel) Enum() *BeginTransactionRequest_IsolationLevel {
	p := new(BeginTransactionRequest_IsolationLevel)
	*p = x
	return p
}

func (x BeginTransactionRequest_IsolationLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BeginTransactionRequest_IsolationLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_hermes_proto_enumTypes[0].Descriptor()
}

func (BeginTransactionRequest_IsolationLevel) Type() protoreflect.EnumType {
	return &file_hermes_proto_enumTypes[0]
}

func (x BeginTransactionRequest_IsolationLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BeginTransactionRequest_IsolationLevel.Descriptor instead.
func (BeginTransactionRequest_IsolationLevel) EnumDescriptor() ([]byte, []int) {
	return file_hermes_proto_rawDescGZIP(), []int{9, 0}
}

type WatchEvent_EventType int32

const (
	WatchEvent_PUT    WatchEvent_EventType = 0
	WatchEvent_DELETE WatchEvent_EventType = 1
)

// Enum value maps for WatchEvent_EventType.
var (
	WatchEvent_EventType_name = map[int32]string{
		0: "PUT",
		1: "DELETE",
	}
	WatchEvent_EventType_value = map[string]int32{
		"PUT":    0,
		"DELETE": 1,
	}
)

func (x WatchEvent_EventType) Enum() *WatchEvent_EventType {
	p := new(WatchEvent_EventType)
	*p = x
	return p
}

func (x WatchEvent_EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WatchEvent_EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_hermes_proto_enumTypes[1].Descriptor()
}

func (WatchEvent_EventType) Type() protoreflect.EnumType {
	return &file_hermes_proto_enumTypes[1]
}

func (x WatchEvent_EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WatchEvent_EventType.Descriptor instead.
func (WatchEvent_EventType) EnumDescriptor() ([]byte, []int) {
	return file_hermes_proto_rawDescGZIP(), []int{16, 0}
}

type PutRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Key             string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value           []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	TtlSeconds      int64                  `protobuf:"varint,3,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	ExpectedVersion int64                  `protobuf:"varint,4,opt,name=expected_version,json=expectedVersion,proto3" json:"expected_version,omitempty"`
	TransactionId   uint64                 `protobuf:"varint,5,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PutRequest) Reset() {
	*x = PutRequest{}
	mi := &file_hermes_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutRequest) ProtoMessage() {}

func (x *PutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hermes_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutRequest.ProtoReflect.Descriptor instead.
func (*PutRequest) Descriptor() ([]byte, []int) {
	return file_hermes_proto_rawDescGZIP(), []int{0}
}

func (x *PutRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *PutRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *PutRequest) GetTtlSeconds() int64 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

func (x *PutRequest) GetExpectedVersion() int64 {
	if x != nil {
		return x.ExpectedVersion
	}
	return 0
}

func (x *PutRequest) GetTransactionId() uint64 {
	if x != nil {
		return x.TransactionId
	}
	return 0
}

type PutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         ErrorCode              `protobuf:"varint,1,opt,name=error,proto3,enum=hermes.ErrorCode" json:"error,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,2,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	Version       int64                  `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	LeaderHint    string                 `protobuf:"bytes,4,opt,name=leader_hint,json=leaderHint,proto3" json:"leader_hint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutResponse) Reset() {
	*x = PutResponse{}
	mi := &file_hermes_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutResponse) ProtoMessage() {}

func (x *PutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hermes_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutResponse.ProtoReflect.Descriptor instead.
func (*PutResponse) Descriptor() ([]byte, []int) {
	return file_hermes_proto_rawDescGZIP(), []int{1}
}

func (x *PutResponse) GetError() ErrorCode {
	if x != nil {
		return x.Error
	}
	return ErrorCode_OK
}

func (x *PutResponse) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

func (x *PutResponse) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *PutResponse) GetLeaderHint() string {
	if x != nil {
		return x.LeaderHint
	}
	return ""
}

type GetRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Key            string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Level          ConsistencyLevel       `protobuf:"varint,2,opt,name=level,proto3,enum=hermes.ConsistencyLevel" json:"level,omitempty"`
	MaxStalenessMs int64                  `protobuf:"varint,3,opt,name=max_staleness_ms,json=maxStalenessMs,proto3" json:"max_staleness_ms,omitempty"`
	ReadTimestamp  int64                  `protobuf:"varint,4,opt,name=read_timestamp,json=readTimestamp,proto3" json:"read_timestamp,omitempty"`
	TransactionId  uint64                 `protobuf:"varint,5,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_hermes_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hermes_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_hermes_proto_rawDescGZIP(), []int{2}
}

func (x *GetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *GetRequest) GetLevel() ConsistencyLevel {
	if x != nil {
		return x.Level
	}
	return ConsistencyLevel_EVENTUAL
}

func (x *GetRequest) GetMaxStalenessMs() int64 {
	if x != nil {
		return x.MaxStalenessMs
	}
	return 0
}

func (x *GetRequest) GetReadTimestamp() int64 {
	if x != nil {
		return x.ReadTimestamp
	}
	return 0
}

func (x *GetRequest) GetTransactionId() uint64 {
	if x != nil {
		return x.TransactionId
	}
	return 0
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         ErrorCode              `protobuf:"varint,1,opt,name=error,proto3,enum=hermes.ErrorCode" json:"error,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,2,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	Value         []byte                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	Version       int64                  `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`
	Timestamp     int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Found         bool                   `protobuf:"varint,6,opt,name=found,proto3" json:"found,omitempty"`
	LeaderHint    string                 `protobuf:"bytes,7,opt,name=leader_hint,json=leaderHint,proto3" json:"leader_hint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_hermes_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hermes_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_hermes_proto_rawDescGZIP(), []int{3}
}

func (x *GetResponse) GetError() ErrorCode {
	if x != nil {
		return x.Error
	}
	return ErrorCode_OK
}

func (x *GetResponse) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

func (x *GetResponse) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *GetResponse) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *GetResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *GetResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *GetResponse) GetLeaderHint() string {
	if x != nil {
		return x.LeaderHint
	}
	return ""
}

type DeleteRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Key             string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	ExpectedVersion int64                  `protobuf:"varint,2,opt,name=expected_version,json=expectedVersion,proto3" json:"expected_version,omitempty"`
	TransactionId   uint64                 `protobuf:"varint,3,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_hermes_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hermes_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_hermes_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *DeleteRequest) GetExpectedVersion() int64 {
	if x != nil {
		return x.ExpectedVersion
	}
	return 0
}

func (x *DeleteRequest) GetTransactionId() uint64 {
	if x != nil {
		return x.TransactionId
	}
	return 0
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         ErrorCode              `protobuf:"varint,1,opt,name=error,proto3,enum=hermes.ErrorCode" json:"error,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,2,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	LeaderHint    string                 `protobuf:"bytes,3,opt,name=leader_hint,json=leaderHint,proto3" json:"leader_hint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_hermes_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hermes_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_hermes_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteResponse) GetError() ErrorCode {
	if x != nil {
		return x.Error
	}
	return ErrorCode_OK
}

func (x *DeleteResponse) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

func (x *DeleteResponse) GetLeaderHint() string {
	if x != nil {
		return x.LeaderHint
	}
	return ""
}

type ScanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartKey      string                 `protobuf:"bytes,1,opt,name=start_key,json=startKey,proto3" json:"start_key,omitempty"`
	EndKey        string                 `protobuf:"bytes,2,opt,name=end_key,json=endKey,proto3" json:"end_key,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Cursor        string                 `protobuf:"bytes,4,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Level         ConsistencyLevel       `protobuf:"varint,5,opt,name=level,proto3,enum=hermes.ConsistencyLevel" json:"level,omitempty"`
	KeysOnly      bool                   `protobuf:"varint,6,opt,name=keys_only,json=keysOnly,proto3" json:"keys_only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanRequest) Reset() {
	*x = ScanRequest{}
	mi := &file_hermes_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanRequest) ProtoMessage() {}

func (x *ScanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hermes_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanRequest.ProtoReflect.Descriptor instead.
func (*ScanRequest) Descriptor() ([]byte, []int) {
	return file_hermes_proto_rawDescGZIP(), []int{6}
}

func (x *ScanRequest) GetStartKey() string {
	if x != nil {
		return x.StartKey
	}
	return ""
}

func (x *ScanRequest) GetEndKey() string {
	if x != nil {
		return x.EndKey
	}
	return ""
}

func (x *ScanRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ScanRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *ScanRequest) GetLevel() ConsistencyLevel {
	if x != nil {
		return x.Level
	}
	return ConsistencyLevel_EVENTUAL
}

func (x *ScanRequest) GetKeysOnly() bool {
	if x != nil {
		return x.KeysOnly
	}
	return false
}

type ScanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         ErrorCode              `protobuf:"varint,1,opt,name=error,proto3,enum=hermes.ErrorCode" json:"error,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,2,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	Items         []*KeyValue            `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	NextCursor    string                 `protobuf:"bytes,4,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	HasMore       bool                   `protobuf:"varint,5,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanResponse) Reset() {
	*x = ScanResponse{}
	mi := &file_hermes_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanResponse) ProtoMessage() {}

func (x *ScanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hermes_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanResponse.ProtoReflect.Descriptor instead.
func (*ScanResponse) Descriptor() ([]byte, []int) {
	return file_hermes_proto_rawDescGZIP(), []int{7}
}

func (x *ScanResponse) GetError() ErrorCode {
	if x != nil {
		return x.Error
	}
	return ErrorCode_OK
}

func (x *ScanResponse) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

func (x *ScanResponse) GetItems() []*KeyValue {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ScanResponse) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

func (x *ScanResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

type KeyValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Version       int64                  `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyValue) Reset() {
	*x = KeyValue{}
	mi := &file_hermes_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyValue) ProtoMessage() {}

func (x *KeyValue) ProtoReflect() protoreflect.Message {
	mi := &file_hermes_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyValue.ProtoReflect.Descriptor instead.
func (*KeyValue) Descriptor() ([]byte, []int) {
	return file_hermes_proto_rawDescGZIP(), []int{8}
}

func (x *KeyValue) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *KeyValue) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *KeyValue) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *KeyValue) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type BeginTransactionRequest struct {
	state         protoimpl.MessageState                 `protogen:"open.v1"`
	Isolation     BeginTransactionRequest_IsolationLevel `protobuf:"varint,1,opt,name=isolation,proto3,enum=hermes.BeginTransactionRequest_IsolationLevel" json:"isolation,omitempty"`
	TimeoutMs     int64                                  `protobuf:"varint,2,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BeginTransactionRequest) Reset() {
	*x = BeginTransactionRequest{}
	mi := &file_hermes_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeginTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeginTransactionRequest) ProtoMessage() {}

func (x *BeginTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hermes_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeginTransactionRequest.ProtoReflect.Descriptor instead.
func (*BeginTransactionRequest) Descriptor() ([]byte, []int) {
	return file_hermes_proto_rawDescGZIP(), []int{9}
}

func (x *BeginTransactionRequest) GetIsolation() BeginTransactionRequest_IsolationLevel {
	if x != nil {
		return x.Isolation
	}
	return BeginTransactionRequest_SNAPSHOT_ISOLATION
}

func (x *BeginTransactionRequest) GetTimeoutMs() int64 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

type BeginTransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         ErrorCode              `protobuf:"varint,1,opt,name=error,proto3,enum=hermes.ErrorCode" json:"error,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,2,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	TransactionId uint64                 `protobuf:"varint,3,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	ReadTimestamp int64                  `protobuf:"varint,4,opt,name=read_timestamp,json=readTimestamp,proto3" json:"read_timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BeginTransactionResponse) Reset() {
	*x = BeginTransactionResponse{}
	mi := &file_hermes_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeginTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeginTransactionResponse) ProtoMessage() {}

func (x *BeginTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hermes_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeginTransactionResponse.ProtoReflect.Descriptor instead.
func (*BeginTransactionResponse) Descriptor() ([]byte, []int) {
	return file_hermes_proto_rawDescGZIP(), []int{10}
}

func (x *BeginTransactionResponse) GetError() ErrorCode {
	if x != nil {
		return x.Error
	}
	return ErrorCode_OK
}

func (x *BeginTransactionResponse) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

func (x *BeginTransactionResponse) GetTransactionId() uint64 {
	if x != nil {
		return x.TransactionId
	}
	return 0
}

func (x *BeginTransactionResponse) GetReadTimestamp() int64 {
	if x != nil {
		return x.ReadTimestamp
	}
	return 0
}

type CommitTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId uint64                 `protobuf:"varint,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitTransactionRequest) Reset() {
	*x = CommitTransactionRequest{}
	mi := &file_hermes_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitTransactionRequest) ProtoMessage() {}

func (x *CommitTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hermes_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitTransactionRequest.ProtoReflect.Descriptor instead.
func (*CommitTransactionRequest) Descriptor() ([]byte, []int) {
	return file_hermes_proto_rawDescGZIP(), []int{11}
}

func (x *CommitTransactionRequest) GetTransactionId() uint64 {
	if x != nil {
		return x.TransactionId
	}
	return 0
}

type CommitTransactionResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Error           ErrorCode              `protobuf:"varint,1,opt,name=error,proto3,enum=hermes.ErrorCode" json:"error,omitempty"`
	ErrorMsg        string                 `protobuf:"bytes,2,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	CommitTimestamp int64                  `protobuf:"varint,3,opt,name=commit_timestamp,json=commitTimestamp,proto3" json:"commit_timestamp,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CommitTransactionResponse) Reset() {
	*x = CommitTransactionResponse{}
	mi := &file_hermes_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitTransactionResponse) ProtoMessage() {}

func (x *CommitTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hermes_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitTransactionResponse.ProtoReflect.Descriptor instead.
func (*CommitTransactionResponse) Descriptor() ([]byte, []int) {
	return file_hermes_proto_rawDescGZIP(), []int{12}
}

func (x *CommitTransactionResponse) GetError() ErrorCode {
	if x != nil {
		return x.Error
	}
	return ErrorCode_OK
}

func (x *CommitTransactionResponse) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

func (x *CommitTransactionResponse) GetCommitTimestamp() int64 {
	if x != nil {
		return x.CommitTimestamp
	}
	return 0
}

type AbortTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId uint64                 `protobuf:"varint,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AbortTransactionRequest) Reset() {
	*x = AbortTransactionRequest{}
	mi := &file_hermes_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbortTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbortTransactionRequest) ProtoMessage() {}

func (x *AbortTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hermes_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbortTransactionRequest.ProtoReflect.Descriptor instead.
func (*AbortTransactionRequest) Descriptor() ([]byte, []int) {
	return file_hermes_proto_rawDescGZIP(), []int{13}
}

func (x *AbortTransactionRequest) GetTransactionId() uint64 {
	if x != nil {
		return x.TransactionId
	}
	return 0
}

type AbortTransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         ErrorCode              `protobuf:"varint,1,opt,name=error,proto3,enum=hermes.ErrorCode" json:"error,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,2,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AbortTransactionResponse) Reset() {
	*x = AbortTransactionResponse{}
	mi := &file_hermes_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbortTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbortTransactionResponse) ProtoMessage() {}

func (x *AbortTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hermes_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbortTransactionResponse.ProtoReflect.Descriptor instead.
func (*AbortTransactionResponse) Descriptor() ([]byte, []int) {
	return file_hermes_proto_rawDescGZIP(), []int{14}
}

func (x *AbortTransactionResponse) GetError() ErrorCode {
	if x != nil {
		return x.Error
	}
	return ErrorCode_OK
}

func (x *AbortTransactionResponse) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type WatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyPrefix     string                 `protobuf:"bytes,1,opt,name=key_prefix,json=keyPrefix,proto3" json:"key_prefix,omitempty"`
	StartVersion  int64                  `protobuf:"varint,2,opt,name=start_version,json=startVersion,proto3" json:"start_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchRequest) Reset() {
	*x = WatchRequest{}
	mi := &file_hermes_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchRequest) ProtoMessage() {}

func (x *WatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hermes_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchRequest.ProtoReflect.Descriptor instead.
func (*WatchRequest) Descriptor() ([]byte, []int) {
	return file_hermes_proto_rawDescGZIP(), []int{15}
}

func (x *WatchRequest) GetKeyPrefix() string {
	if x != nil {
		return x.KeyPrefix
	}
	return ""
}

func (x *WatchRequest) GetStartVersion() int64 {
	if x != nil {
		return x.StartVersion
	}
	return 0
}

type WatchEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          WatchEvent_EventType   `protobuf:"varint,1,opt,name=type,proto3,enum=hermes.WatchEvent_EventType" json:"type,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	Version       int64                  `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`
	Timestamp     int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchEvent) Reset() {
	*x = WatchEvent{}
	mi := &file_hermes_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchEvent) ProtoMessage() {}

func (x *WatchEvent) ProtoReflect() protoreflect.Message {
	mi := &file_hermes_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchEvent.ProtoReflect.Descriptor instead.
func (*WatchEvent) Descriptor() ([]byte, []int) {
	return file_hermes_proto_rawDescGZIP(), []int{16}
}

func (x *WatchEvent) GetType() WatchEvent_EventType {
	if x != nil {
		return x.Type
	}
	return WatchEvent_PUT
}

func (x *WatchEvent) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *WatchEvent) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *WatchEvent) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *WatchEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_hermes_proto protoreflect.FileDescriptor

const file_hermes_proto_rawDesc = "" +
	"\n" +
	"\fhermes.proto\x12\x06hermes\x1a\fcommon.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa7\x01\n" +
	"\n" +
	"PutRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\x12\x1f\n" +
	"\vttl_seconds\x18\x03 \x01(\x03R\n" +
	"ttlSeconds\x12)\n" +
	"\x10expected_version\x18\x04 \x01(\x03R\x0fexpectedVersion\x12%\n" +
	"\x0etransaction_id\x18\x05 \x01(\x04R\rtransactionId\"\x8e\x01\n" +
	"\vPutResponse\x12'\n" +
	"\x05error\x18\x01 \x01(\x0e2\x11.hermes.ErrorCodeR\x05error\x12\x1b\n" +
	"\terror_msg\x18\x02 \x01(\tR\berrorMsg\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x03R\aversion\x12\x1f\n" +
	"\vleader_hint\x18\x04 \x01(\tR\n" +
	"leaderHint\"\xc6\x01\n" +
	"\n" +
	"GetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12.\n" +
	"\x05level\x18\x02 \x01(\x0e2\x18.hermes.ConsistencyLevelR\x05level\x12(\n" +
	"\x10max_staleness_ms\x18\x03 \x01(\x03R\x0emaxStalenessMs\x12%\n" +
	"\x0eread_timestamp\x18\x04 \x01(\x03R\rreadTimestamp\x12%\n" +
	"\x0etransaction_id\x18\x05 \x01(\x04R\rtransactionId\"\xd8\x01\n" +
	"\vGetResponse\x12'\n" +
	"\x05error\x18\x01 \x01(\x0e2\x11.hermes.ErrorCodeR\x05error\x12\x1b\n" +
	"\terror_msg\x18\x02 \x01(\tR\berrorMsg\x12\x14\n" +
	"\x05value\x18\x03 \x01(\fR\x05value\x12\x18\n" +
	"\aversion\x18\x04 \x01(\x03R\aversion\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\x12\x14\n" +
	"\x05found\x18\x06 \x01(\bR\x05found\x12\x1f\n" +
	"\vleader_hint\x18\a \x01(\tR\n" +
	"leaderHint\"s\n" +
	"\rDeleteRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12)\n" +
	"\x10expected_version\x18\x02 \x01(\x03R\x0fexpectedVersion\x12%\n" +
	"\x0etransaction_id\x18\x03 \x01(\x04R\rtransactionId\"w\n" +
	"\x0eDeleteResponse\x12'\n" +
	"\x05error\x18\x01 \x01(\x0e2\x11.hermes.ErrorCodeR\x05error\x12\x1b\n" +
	"\terror_msg\x18\x02 \x01(\tR\berrorMsg\x12\x1f\n" +
	"\vleader_hint\x18\x03 \x01(\tR\n" +
	"leaderHint\"\xbe\x01\n" +
	"\vScanRequest\x12\x1b\n" +
	"\tstart_key\x18\x01 \x01(\tR\bstartKey\x12\x17\n" +
	"\aend_key\x18\x02 \x01(\tR\x06endKey\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06cursor\x18\x04 \x01(\tR\x06cursor\x12.\n" +
	"\x05level\x18\x05 \x01(\x0e2\x18.hermes.ConsistencyLevelR\x05level\x12\x1b\n" +
	"\tkeys_only\x18\x06 \x01(\bR\bkeysOnly\"\xb8\x01\n" +
	"\fScanResponse\x12'\n" +
	"\x05error\x18\x01 \x01(\x0e2\x11.hermes.ErrorCodeR\x05error\x12\x1b\n" +
	"\terror_msg\x18\x02 \x01(\tR\berrorMsg\x12&\n" +
	"\x05items\x18\x03 \x03(\v2\x10.hermes.KeyValueR\x05items\x12\x1f\n" +
	"\vnext_cursor\x18\x04 \x01(\tR\n" +
	"nextCursor\x12\x19\n" +
	"\bhas_more\x18\x05 \x01(\bR\ahasMore\"j\n" +
	"\bKeyValue\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x03R\aversion\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\"\xd6\x01\n" +
	"\x17BeginTransactionRequest\x12L\n" +
	"\tisolation\x18\x01 \x01(\x0e2..hermes.BeginTransactionRequest.IsolationLevelR\tisolation\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x02 \x01(\x03R\ttimeoutMs\"N\n" +
	"\x0eIsolationLevel\x12\x16\n" +
	"\x12SNAPSHOT_ISOLATION\x10\x00\x12\x10\n" +
	"\fSERIALIZABLE\x10\x01\x12\x12\n" +
	"\x0eREAD_COMMITTED\x10\x02\"\xae\x01\n" +
	"\x18BeginTransactionResponse\x12'\n" +
	"\x05error\x18\x01 \x01(\x0e2\x11.hermes.ErrorCodeR\x05error\x12\x1b\n" +
	"\terror_msg\x18\x02 \x01(\tR\berrorMsg\x12%\n" +
	"\x0etransaction_id\x18\x03 \x01(\x04R\rtransactionId\x12%\n" +
	"\x0eread_timestamp\x18\x04 \x01(\x03R\rreadTimestamp\"A\n" +
	"\x18CommitTransactionRequest\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\x04R\rtransactionId\"\x8c\x01\n" +
	"\x19CommitTransactionResponse\x12'\n" +
	"\x05error\x18\x01 \x01(\x0e2\x11.hermes.ErrorCodeR\x05error\x12\x1b\n" +
	"\terror_msg\x18\x02 \x01(\tR\berrorMsg\x12)\n" +
	"\x10commit_timestamp\x18\x03 \x01(\x03R\x0fcommitTimestamp\"@\n" +
	"\x17AbortTransactionRequest\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\x04R\rtransactionId\"`\n" +
	"\x18AbortTransactionResponse\x12'\n" +
	"\x05error\x18\x01 \x01(\x0e2\x11.hermes.ErrorCodeR\x05error\x12\x1b\n" +
	"\terror_msg\x18\x02 \x01(\tR\berrorMsg\"R\n" +
	"\fWatchRequest\x12\x1d\n" +
	"\n" +
	"key_prefix\x18\x01 \x01(\tR\tkeyPrefix\x12#\n" +
	"\rstart_version\x18\x02 \x01(\x03R\fstartVersion\"\xc0\x01\n" +
	"\n" +
	"WatchEvent\x120\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1c.hermes.WatchEvent.EventTypeR\x04type\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x03 \x01(\fR\x05value\x12\x18\n" +
	"\aversion\x18\x04 \x01(\x03R\aversion\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\" \n" +
	"\tEventType\x12\a\n" +
	"\x03PUT\x10\x00\x12\n" +
	"\n" +
	"\x06DELETE\x10\x012\xcc\x04\n" +
	"\bHermesKV\x12.\n" +
	"\x03Put\x12\x12.hermes.PutRequest\x1a\x13.hermes.PutResponse\x12.\n" +
	"\x03Get\x12\x12.hermes.GetRequest\x1a\x13.hermes.GetResponse\x127\n" +
	"\x06Delete\x12\x15.hermes.DeleteRequest\x1a\x16.hermes.DeleteResponse\x121\n" +
	"\x04Scan\x12\x13.hermes.ScanRequest\x1a\x14.hermes.ScanResponse\x12U\n" +
	"\x10BeginTransaction\x12\x1f.hermes.BeginTransactionRequest\x1a .hermes.BeginTransactionResponse\x12X\n" +
	"\x11CommitTransaction\x12 .hermes.CommitTransactionRequest\x1a!.hermes.CommitTransactionResponse\x12U\n" +
	"\x10AbortTransaction\x12\x1f.hermes.AbortTransactionRequest\x1a .hermes.AbortTransactionResponse\x123\n" +
	"\x05Watch\x12\x14.hermes.WatchRequest\x1a\x12.hermes.WatchEvent0\x01\x127\n" +
	"\bBatchOps\x12\x12.hermes.PutRequest\x1a\x13.hermes.PutResponse(\x010\x01B+Z)github.com/aadityabinodyadav/hermes/protob\x06proto3"

var (
	file_hermes_proto_rawDescOnce sync.Once
	file_hermes_proto_rawDescData []byte
)

func file_hermes_proto_rawDescGZIP() []byte {
	file_hermes_proto_rawDescOnce.Do(func() {
		file_hermes_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hermes_proto_rawDesc), len(file_hermes_proto_rawDesc)))
	})
	return file_hermes_proto_rawDescData
}

var file_hermes_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_hermes_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_hermes_proto_goTypes = []any{
	(BeginTransactionRequest_IsolationLevel)(0), // 0: hermes.BeginTransactionRequest.IsolationLevel
	(WatchEvent_EventType)(0),                   // 1: hermes.WatchEvent.EventType
	(*PutRequest)(nil),                          // 2: hermes.PutRequest
	(*PutResponse)(nil),                         // 3: hermes.PutResponse
	(*GetRequest)(nil),                          // 4: hermes.GetRequest
	(*GetResponse)(nil),                         // 5: hermes.GetResponse
	(*DeleteRequest)(nil),                       // 6: hermes.DeleteRequest
	(*DeleteResponse)(nil),                      // 7: hermes.DeleteResponse
	(*ScanRequest)(nil),                         // 8: hermes.ScanRequest
	(*ScanResponse)(nil),                        // 9: hermes.ScanResponse
	(*KeyValue)(nil),                            // 10: hermes.KeyValue
	(*BeginTransactionRequest)(nil),             // 11: hermes.BeginTransactionRequest
	(*BeginTransactionResponse)(nil),            // 12: hermes.BeginTransactionResponse
	(*CommitTransactionRequest)(nil),            // 13: hermes.CommitTransactionRequest
	(*CommitTransactionResponse)(nil),           // 14: hermes.CommitTransactionResponse
	(*AbortTransactionRequest)(nil),             // 15: hermes.AbortTransactionRequest
	(*AbortTransactionResponse)(nil),            // 16: hermes.AbortTransactionResponse
	(*WatchRequest)(nil),                        // 17: hermes.WatchRequest
	(*WatchEvent)(nil),                          // 18: hermes.WatchEvent
	(ErrorCode)(0),                              // 19: hermes.ErrorCode
	(ConsistencyLevel)(0),                       // 20: hermes.ConsistencyLevel
}
var file_hermes_proto_depIdxs = []int32{
	19, // 0: hermes.PutResponse.error:type_name -> hermes.ErrorCode
	20, // 1: hermes.GetRequest.level:type_name -> hermes.ConsistencyLevel
	19, // 2: hermes.GetResponse.error:type_name -> hermes.ErrorCode
	19, // 3: hermes.DeleteResponse.error:type_name -> hermes.ErrorCode
	20, // 4: hermes.ScanRequest.level:type_name -> hermes.ConsistencyLevel
	19, // 5: hermes.ScanResponse.error:type_name -> hermes.ErrorCode
	10, // 6: hermes.ScanResponse.items:type_name -> hermes.KeyValue
	0,  // 7: hermes.BeginTransactionRequest.isolation:type_name -> hermes.BeginTransactionRequest.IsolationLevel
	19, // 8: hermes.BeginTransactionResponse.error:type_name -> hermes.ErrorCode
	19, // 9: hermes.CommitTransactionResponse.error:type_name -> hermes.ErrorCode
	19, // 10: hermes.AbortTransactionResponse.error:type_name -> hermes.ErrorCode
	1,  // 11: hermes.WatchEvent.type:type_name -> hermes.WatchEvent.EventType
	2,  // 12: hermes.HermesKV.Put:input_type -> hermes.PutRequest
	4,  // 13: hermes.HermesKV.Get:input_type -> hermes.GetRequest
	6,  // 14: hermes.HermesKV.Delete:input_type -> hermes.DeleteRequest
	8,  // 15: hermes.HermesKV.Scan:input_type -> hermes.ScanRequest
	11, // 16: hermes.HermesKV.BeginTransaction:input_type -> hermes.BeginTransactionRequest
	13, // 17: hermes.HermesKV.CommitTransaction:input_type -> hermes.CommitTransactionRequest
	15, // 18: hermes.HermesKV.AbortTransaction:input_type -> hermes.AbortTransactionRequest
	17, // 19: hermes.HermesKV.Watch:input_type -> hermes.WatchRequest
	2,  // 20: hermes.HermesKV.BatchOps:input_type -> hermes.PutRequest
	3,  // 21: hermes.HermesKV.Put:output_type -> hermes.PutResponse
	5,  // 22: hermes.HermesKV.Get:output_type -> hermes.GetResponse
	7,  // 23: hermes.HermesKV.Delete:output_type -> hermes.DeleteResponse
	9,  // 24: hermes.HermesKV.Scan:output_type -> hermes.ScanResponse
	12, // 25: hermes.HermesKV.BeginTransaction:output_type -> hermes.BeginTransactionResponse
	14, // 26: hermes.HermesKV.CommitTransaction:output_type -> hermes.CommitTransactionResponse
	16, // 27: hermes.HermesKV.AbortTransaction:output_type -> hermes.AbortTransactionResponse
	18, // 28: hermes.HermesKV.Watch:output_type -> hermes.WatchEvent
	3,  // 29: hermes.HermesKV.BatchOps:output_type -> hermes.PutResponse
	21, // [21:30] is the sub-list for method output_type
	12, // [12:21] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_hermes_proto_init() }
func file_hermes_proto_init() {
	if File_hermes_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hermes_proto_rawDesc), len(file_hermes_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_hermes_proto_goTypes,
		DependencyIndexes: file_hermes_proto_depIdxs,
		EnumInfos:         file_hermes_proto_enumTypes,
		MessageInfos:      file_hermes_proto_msgTypes,
	}.Build()
	File_hermes_proto = out.File
	file_hermes_proto_goTypes = nil
	file_hermes_proto_depIdxs = nil
}
