// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: membership.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MemberState int32

const (
	MemberState_ALIVE     MemberState = 0
	MemberState_SUSPECTED MemberState = 1
	MemberState_DEAD      MemberState = 2
	MemberState_LEFT      MemberState = 3
)

// Enum value maps for MemberState.
var (
	MemberState_name = map[int32]string{
		0: "ALIVE",
		1: "SUSPECTED",
		2: "DEAD",
		3: "LEFT",
	}
	MemberState_value = map[string]int32{
		"ALIVE":     0,
		"SUSPECTED": 1,
		"DEAD":      2,
		"LEFT":      3,
	}
)

func (x MemberState) Enum() *MemberState {
	p := new(MemberState)
	*p = x
	return p
}

func (x MemberState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MemberState) Descriptor() protoreflect.EnumDescriptor {
	return file_membership_proto_enumTypes[0].Descriptor()
}

func (MemberState) Type() protoreflect.EnumType {
	return &file_membership_proto_enumTypes[0]
}

func (x MemberState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MemberState.Descriptor instead.
func (MemberState) EnumDescriptor() ([]byte, []int) {
	return file_membership_proto_rawDescGZIP(), []int{0}
}

type Member struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Info          *NodeInfo              `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	State         MemberState            `protobuf:"varint,2,opt,name=state,proto3,enum=hermes.MemberState" json:"state,omitempty"`
	Incarnation   uint64                 `protobuf:"varint,3,opt,name=incarnation,proto3" json:"incarnation,omitempty"`
	LastSeen      int64                  `protobuf:"varint,4,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Member) Reset() {
	*x = Member{}
	mi := &file_membership_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Member) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Member) ProtoMessage() {}

func (x *Member) ProtoReflect() protoreflect.Message {
	mi := &file_membership_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Member.ProtoReflect.Descriptor instead.
func (*Member) Descriptor() ([]byte, []int) {
	return file_membership_proto_rawDescGZIP(), []int{0}
}

func (x *Member) GetInfo() *NodeInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *Member) GetState() MemberState {
	if x != nil {
		return x.State
	}
	return MemberState_ALIVE
}

func (x *Member) GetIncarnation() uint64 {
	if x != nil {
		return x.Incarnation
	}
	return 0
}

func (x *Member) GetLastSeen() int64 {
	if x != nil {
		return x.LastSeen
	}
	return 0
}

type PingRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SenderId       string                 `protobuf:"bytes,1,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	SequenceNumber uint64                 `protobuf:"varint,2,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	GossipUpdates  []*Member              `protobuf:"bytes,3,rep,name=gossip_updates,json=gossipUpdates,proto3" json:"gossip_updates,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_membership_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_membership_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_membership_proto_rawDescGZIP(), []int{1}
}

func (x *PingRequest) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *PingRequest) GetSequenceNumber() uint64 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

func (x *PingRequest) GetGossipUpdates() []*Member {
	if x != nil {
		return x.GossipUpdates
	}
	return nil
}

type PingResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SenderId       string                 `protobuf:"bytes,1,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	SequenceNumber uint64                 `protobuf:"varint,2,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	GossipUpdates  []*Member              `protobuf:"bytes,3,rep,name=gossip_updates,json=gossipUpdates,proto3" json:"gossip_updates,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_membership_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_membership_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_membership_proto_rawDescGZIP(), []int{2}
}

func (x *PingResponse) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *PingResponse) GetSequenceNumber() uint64 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

func (x *PingResponse) GetGossipUpdates() []*Member {
	if x != nil {
		return x.GossipUpdates
	}
	return nil
}

type PingReqRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SenderId       string                 `protobuf:"bytes,1,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	TargetId       string                 `protobuf:"bytes,2,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	SequenceNumber uint64                 `protobuf:"varint,3,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PingReqRequest) Reset() {
	*x = PingReqRequest{}
	mi := &file_membership_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingReqRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingReqRequest) ProtoMessage() {}

func (x *PingReqRequest) ProtoReflect() protoreflect.Message {
	mi := &file_membership_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingReqRequest.ProtoReflect.Descriptor instead.
func (*PingReqRequest) Descriptor() ([]byte, []int) {
	return file_membership_proto_rawDescGZIP(), []int{3}
}

func (x *PingReqRequest) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *PingReqRequest) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *PingReqRequest) GetSequenceNumber() uint64 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

type PingReqResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Reached        bool                   `protobuf:"varint,1,opt,name=reached,proto3" json:"reached,omitempty"`
	SequenceNumber uint64                 `protobuf:"varint,2,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	GossipUpdates  []*Member              `protobuf:"bytes,3,rep,name=gossip_updates,json=gossipUpdates,proto3" json:"gossip_updates,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PingReqResponse) Reset() {
	*x = PingReqResponse{}
	mi := &file_membership_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingReqResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingReqResponse) ProtoMessage() {}

func (x *PingReqResponse) ProtoReflect() protoreflect.Message {
	mi := &file_membership_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingReqResponse.ProtoReflect.Descriptor instead.
func (*PingReqResponse) Descriptor() ([]byte, []int) {
	return file_membership_proto_rawDescGZIP(), []int{4}
}

func (x *PingReqResponse) GetReached() bool {
	if x != nil {
		return x.Reached
	}
	return false
}

func (x *PingReqResponse) GetSequenceNumber() uint64 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

func (x *PingReqResponse) GetGossipUpdates() []*Member {
	if x != nil {
		return x.GossipUpdates
	}
	return nil
}

type JoinRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeInfo      *NodeInfo              `protobuf:"bytes,1,opt,name=node_info,json=nodeInfo,proto3" json:"node_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRequest) Reset() {
	*x = JoinRequest{}
	mi := &file_membership_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRequest) ProtoMessage() {}

func (x *JoinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_membership_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRequest.ProtoReflect.Descriptor instead.
func (*JoinRequest) Descriptor() ([]byte, []int) {
	return file_membership_proto_rawDescGZIP(), []int{5}
}

func (x *JoinRequest) GetNodeInfo() *NodeInfo {
	if x != nil {
		return x.NodeInfo
	}
	return nil
}

type JoinResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Members       []*Member              `protobuf:"bytes,3,rep,name=members,proto3" json:"members,omitempty"`
	ClusterId     string                 `protobuf:"bytes,4,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinResponse) Reset() {
	*x = JoinResponse{}
	mi := &file_membership_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinResponse) ProtoMessage() {}

func (x *JoinResponse) ProtoReflect() protoreflect.Message {
	mi := &file_membership_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinResponse.ProtoReflect.Descriptor instead.
func (*JoinResponse) Descriptor() ([]byte, []int) {
	return file_membership_proto_rawDescGZIP(), []int{6}
}

func (x *JoinResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *JoinResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *JoinResponse) GetMembers() []*Member {
	if x != nil {
		return x.Members
	}
	return nil
}

func (x *JoinResponse) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

type LeaveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveRequest) Reset() {
	*x = LeaveRequest{}
	mi := &file_membership_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveRequest) ProtoMessage() {}

func (x *LeaveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_membership_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveRequest.ProtoReflect.Descriptor instead.
func (*LeaveRequest) Descriptor() ([]byte, []int) {
	return file_membership_proto_rawDescGZIP(), []int{7}
}

func (x *LeaveRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *LeaveRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type LeaveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveResponse) Reset() {
	*x = LeaveResponse{}
	mi := &file_membership_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveResponse) ProtoMessage() {}

func (x *LeaveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_membership_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveResponse.ProtoReflect.Descriptor instead.
func (*LeaveResponse) Descriptor() ([]byte, []int) {
	return file_membership_proto_rawDescGZIP(), []int{8}
}

func (x *LeaveResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ClusterStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequesterId   string                 `protobuf:"bytes,1,opt,name=requester_id,json=requesterId,proto3" json:"requester_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterStateRequest) Reset() {
	*x = ClusterStateRequest{}
	mi := &file_membership_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterStateRequest) ProtoMessage() {}

func (x *ClusterStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_membership_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterStateRequest.ProtoReflect.Descriptor instead.
func (*ClusterStateRequest) Descriptor() ([]byte, []int) {
	return file_membership_proto_rawDescGZIP(), []int{9}
}

func (x *ClusterStateRequest) GetRequesterId() string {
	if x != nil {
		return x.RequesterId
	}
	return ""
}

type ClusterStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Members       []*Member              `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
	ClusterId     string                 `protobuf:"bytes,2,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	Epoch         uint64                 `protobuf:"varint,3,opt,name=epoch,proto3" json:"epoch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterStateResponse) Reset() {
	*x = ClusterStateResponse{}
	mi := &file_membership_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterStateResponse) ProtoMessage() {}

func (x *ClusterStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_membership_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterStateResponse.ProtoReflect.Descriptor instead.
func (*ClusterStateResponse) Descriptor() ([]byte, []int) {
	return file_membership_proto_rawDescGZIP(), []int{10}
}

func (x *ClusterStateResponse) GetMembers() []*Member {
	if x != nil {
		return x.Members
	}
	return nil
}

func (x *ClusterStateResponse) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *ClusterStateResponse) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

var File_membership_proto protoreflect.FileDescriptor

const file_membership_proto_rawDesc = "" +
	"\n" +
	"\x10membership.proto\x12\x06hermes\x1a\fcommon.proto\"\x98\x01\n" +
	"\x06Member\x12$\n" +
	"\x04info\x18\x01 \x01(\v2\x10.hermes.NodeInfoR\x04info\x12)\n" +
	"\x05state\x18\x02 \x01(\x0e2\x13.hermes.MemberStateR\x05state\x12 \n" +
	"\vincarnation\x18\x03 \x01(\x04R\vincarnation\x12\x1b\n" +
	"\tlast_seen\x18\x04 \x01(\x03R\blastSeen\"\x8a\x01\n" +
	"\vPingRequest\x12\x1b\n" +
	"\tsender_id\x18\x01 \x01(\tR\bsenderId\x12'\n" +
	"\x0fsequence_number\x18\x02 \x01(\x04R\x0esequenceNumber\x125\n" +
	"\x0egossip_updates\x18\x03 \x03(\v2\x0e.hermes.MemberR\rgossipUpdates\"\x8b\x01\n" +
	"\fPingResponse\x12\x1b\n" +
	"\tsender_id\x18\x01 \x01(\tR\bsenderId\x12'\n" +
	"\x0fsequence_number\x18\x02 \x01(\x04R\x0esequenceNumber\x125\n" +
	"\x0egossip_updates\x18\x03 \x03(\v2\x0e.hermes.MemberR\rgossipUpdates\"s\n" +
	"\x0ePingReqRequest\x12\x1b\n" +
	"\tsender_id\x18\x01 \x01(\tR\bsenderId\x12\x1b\n" +
	"\ttarget_id\x18\x02 \x01(\tR\btargetId\x12'\n" +
	"\x0fsequence_number\x18\x03 \x01(\x04R\x0esequenceNumber\"\x8b\x01\n" +
	"\x0fPingReqResponse\x12\x18\n" +
	"\areached\x18\x01 \x01(\bR\areached\x12'\n" +
	"\x0fsequence_number\x18\x02 \x01(\x04R\x0esequenceNumber\x125\n" +
	"\x0egossip_updates\x18\x03 \x03(\v2\x0e.hermes.MemberR\rgossipUpdates\"<\n" +
	"\vJoinRequest\x12-\n" +
	"\tnode_info\x18\x01 \x01(\v2\x10.hermes.NodeInfoR\bnodeInfo\"\x89\x01\n" +
	"\fJoinResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12(\n" +
	"\amembers\x18\x03 \x03(\v2\x0e.hermes.MemberR\amembers\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x04 \x01(\tR\tclusterId\"?\n" +
	"\fLeaveRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\")\n" +
	"\rLeaveResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"8\n" +
	"\x13ClusterStateRequest\x12!\n" +
	"\frequester_id\x18\x01 \x01(\tR\vrequesterId\"u\n" +
	"\x14ClusterStateResponse\x12(\n" +
	"\amembers\x18\x01 \x03(\v2\x0e.hermes.MemberR\amembers\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x02 \x01(\tR\tclusterId\x12\x14\n" +
	"\x05epoch\x18\x03 \x01(\x04R\x05epoch*;\n" +
	"\vMemberState\x12\t\n" +
	"\x05ALIVE\x10\x00\x12\r\n" +
	"\tSUSPECTED\x10\x01\x12\b\n" +
	"\x04DEAD\x10\x02\x12\b\n" +
	"\x04LEFT\x10\x032\x82\x03\n" +
	"\x11MembershipService\x121\n" +
	"\x04Ping\x12\x13.hermes.PingRequest\x1a\x14.hermes.PingResponse\x12:\n" +
	"\aPingReq\x12\x16.hermes.PingReqRequest\x1a\x17.hermes.PingReqResponse\x121\n" +
	"\x04Join\x12\x13.hermes.JoinRequest\x1a\x14.hermes.JoinResponse\x124\n" +
	"\x05Leave\x12\x14.hermes.LeaveRequest\x1a\x15.hermes.LeaveResponse\x12L\n" +
	"\x0fGetClusterState\x12\x1b.hermes.ClusterStateRequest\x1a\x1c.hermes.ClusterStateResponse\x12G\n" +
	"\x16StreamMembershipEvents\x12\x1b.hermes.ClusterStateRequest\x1a\x0e.hermes.Member0\x01B+Z)github.com/aadityabinodyadav/hermes/protob\x06proto3"

var (
	file_membership_proto_rawDescOnce sync.Once
	file_membership_proto_rawDescData []byte
)

func file_membership_proto_rawDescGZIP() []byte {
	file_membership_proto_rawDescOnce.Do(func() {
		file_membership_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_membership_proto_rawDesc), len(file_membership_proto_rawDesc)))
	})
	return file_membership_proto_rawDescData
}

var file_membership_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_membership_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_membership_proto_goTypes = []any{
	(MemberState)(0),             // 0: hermes.MemberState
	(*Member)(nil),               // 1: hermes.Member
	(*PingRequest)(nil),          // 2: hermes.PingRequest
	(*PingResponse)(nil),         // 3: hermes.PingResponse
	(*PingReqRequest)(nil),       // 4: hermes.PingReqRequest
	(*PingReqResponse)(nil),      // 5: hermes.PingReqResponse
	(*JoinRequest)(nil),          // 6: hermes.JoinRequest
	(*JoinResponse)(nil),         // 7: hermes.JoinResponse
	(*LeaveRequest)(nil),         // 8: hermes.LeaveRequest
	(*LeaveResponse)(nil),        // 9: hermes.LeaveResponse
	(*ClusterStateRequest)(nil),  // 10: hermes.ClusterStateRequest
	(*ClusterStateResponse)(nil), // 11: hermes.ClusterStateResponse
	(*NodeInfo)(nil),             // 12: hermes.NodeInfo
}
var file_membership_proto_depIdxs = []int32{
	12, // 0: hermes.Member.info:type_name -> hermes.NodeInfo
	0,  // 1: hermes.Member.state:type_name -> hermes.MemberState
	1,  // 2: hermes.PingRequest.gossip_updates:type_name -> hermes.Member
	1,  // 3: hermes.PingResponse.gossip_updates:type_name -> hermes.Member
	1,  // 4: hermes.PingReqResponse.gossip_updates:type_name -> hermes.Member
	12, // 5: hermes.JoinRequest.node_info:type_name -> hermes.NodeInfo
	1,  // 6: hermes.JoinResponse.members:type_name -> hermes.Member
	1,  // 7: hermes.ClusterStateResponse.members:type_name -> hermes.Member
	2,  // 8: hermes.MembershipService.Ping:input_type -> hermes.PingRequest
	4,  // 9: hermes.MembershipService.PingReq:input_type -> hermes.PingReqRequest
	6,  // 10: hermes.MembershipService.Join:input_type -> hermes.JoinRequest
	8,  // 11: hermes.MembershipService.Leave:input_type -> hermes.LeaveRequest
	10, // 12: hermes.MembershipService.GetClusterState:input_type -> hermes.ClusterStateRequest
	10, // 13: hermes.MembershipService.StreamMembershipEvents:input_type -> hermes.ClusterStateRequest
	3,  // 14: hermes.MembershipService.Ping:output_type -> hermes.PingResponse
	5,  // 15: hermes.MembershipService.PingReq:output_type -> hermes.PingReqResponse
	7,  // 16: hermes.MembershipService.Join:output_type -> hermes.JoinResponse
	9,  // 17: hermes.MembershipService.Leave:output_type -> hermes.LeaveResponse
	11, // 18: hermes.MembershipService.GetClusterState:output_type -> hermes.ClusterStateResponse
	1,  // 19: hermes.MembershipService.StreamMembershipEvents:output_type -> hermes.Member
	14, // [14:20] is the sub-list for method output_type
	8,  // [8:14] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_membership_proto_init() }
func file_membership_proto_init() {
	if File_membership_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_membership_proto_rawDesc), len(file_membership_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_membership_proto_goTypes,
		DependencyIndexes: file_membership_proto_depIdxs,
		EnumInfos:         file_membership_proto_enumTypes,
		MessageInfos:      file_membership_proto_msgTypes,
	}.Build()
	File_membership_proto = out.File
	file_membership_proto_goTypes = nil
	file_membership_proto_depIdxs = nil
}
